### PR TITLE
No need to subclass Disposable

### PR DESCRIPTION
**Pull request by md2perpe**
The registries don't need Disposable.
It's enough with implementing { dispose }.

### CODE REVIEW

**Comment by eamodio** [comment]
Thank you for the contribution! Although I do have a question about it -- what is the benefit here? Why should I not extend from `Disposable`?

**Comment by md2perpe** [comment]
You only need to expose a method `dispose()`; no behaviour from `Disposable` is needed. Therefore no inheritance is needed.

Think of the `Disposable` class as a helper, not as a base class. Your use of it inside your class by creating an instance `this._disposable` is the correct way to use it; inheriting it is (mostly) not.

Here are a couple of articles about inheritance vs implementing an interface:
* https://www.javaworld.com/article/2073649/core-java/why-extends-is-evil.html
* https://msdn.microsoft.com/en-us/library/ms973861.aspx?f=255&MSPPError=-2147217396#interinher_topic4

Also, the code reduces somewhat by just implementing the interface since you don't need to call the super class constructor.

**Comment by eamodio** [comment]
To be clear, I'm well aware of the differences between inheritance and implementing an interface. From my perspective while I would agree that given the version of `Disposable` exposed to extensions (vs the version in vscode itself) there is little to no value in extending (inheriting) from `Disposable` other than contract enforcement (which of course would also be provided by just implementing the interface), yet there is also very little cost. Yes by extending from it, I am carrying along an extra reference in the prototype chain, but that imo is of little concern.

Never the less, I'm still inclined to accept the PR with some modifications -- I still want the contract enforced (so that a build error will be triggered if the `dispose` method was typo'd, deleted, etc) so please re-add `implements Disposable`. Also please resolve the conflicts as the code has changed.

**Comment by md2perpe** [comment]
Rebased into a single commit.

**Pull request merged**
